compile: heat_map_integrals.cpp
	g++ heat_map_integrals.cpp -I/usr/include/python3.10  -lpython3.10 -lpthread -o  app.out  -Ofast
single : heat_map_integrals_single.cpp
	g++ heat_map_integrals_single.cpp -I/usr/include/python3.10  -lpython3.10 -lpthread -o  app.out  -Ofast
clean:
	rm *.out *.png 
